@echo off
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
start matrix.bat
start images.jpg
timeout 10
start matrix.bat
start images.jpg