@echo off
timeout 1
start matrix.bat
start images.jpg
timeout 1
start matrix.bat
start images.jpg
timeout 1
start matrix.bat
start images.jpg
timeout 1
start matrix.bat
start images.jpg
timeout 10
start matrix.bat
start images.jpg